language: php

php:
  - 7.0

env:
  - illuminateVersion="^5.5"
  - guzzleVersion="^6.3"

install:
   - composer require illuminate/support:${illuminateVersion}
   - composer require guzzlehttp/guzzle:${guzzleVersion}
   - php vendor/autoload.php